#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and "Hi" in the 9th
i="0"

while [ $i -lt 10 ]
do
echo "Holberton School"
if [ $i = 8 ]
then
echo "Hi"
fi
i=$((i+1))
done
