#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
hr="0"
i="1"

while [ $hr -lt 13 ]
do
	echo "Hour: $hr"
	while [ $i -lt 60 ]
	do	
		echo "$i"
		i=$((i+1))
	done
	i="1"
	hr=$((hr+1))
done
