#!/usr/bin/env bash
#Bash script that configures an ubuntu server with:
# localhost resolves to 127.0.0.1
# facebook.com resolves 8.8.8.8
cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -a facebook.com 8.8.8.8 ~/hosts.new
cp -f ~/hosts.new /etc/hosts
